### ISSUE TITLE
Whats new in v5?

### ISSUE THREAD

**Issue by rasmusbe** [jonschlinkert/matched#11]
Hi,

Changelog for v5 released on npm seems to be missing and I don't see any commits made to this repo.

Best regards!

**Comment by jonschlinkert** [comment]
Ha, sorry I just realized (thanks to @doowb) that I didn't push up the release yesterday. Apologies! More detail is in the readme [here](https://github.com/jonschlinkert/matched#v41).

**Comment by rasmusbe** [comment]
Thanks! And 4.1 in the readme is 5.0 in NPM?

**Comment by jonschlinkert** [comment]
Readme needs to be fixed. Want to do a PR?

**Comment by rasmusbe** [comment]
Sure, done in #12
