### ISSUE TITLE
Promise is not a constructor

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/matched#6]
https://github.com/rollup/rollup-plugin-multi-entry/issues/11

**Comment by eventualbuddha** [comment]
My guess is this is due to the [clever use of lazy loading](https://github.com/jonschlinkert/matched/blob/ea1da09c777c4e636b25d2223d3409585da742e7/lib/utils.js#L14)?

**Comment by TrySound** [comment]
@jonschlinkert Do you have a plan to get rid from 0.10? Or you are waiting october?

**Comment by jonschlinkert** [comment]
@TrySound sorry I haven't even had a chance to review this yet. I can add you to the repo if you want

> My guess is this is due to the clever use of lazy loading?

Not as clever as transpiling and blaming lack of support for vanilla javascript getters on another library. jk.  It might be a combination of my misunderstanding of the promise API when I wrote this.

Or is there something specific about the issue that makes you think it's lazy-cache? Or something in the code you can point out as being problematic?

**Comment by jonschlinkert** [comment]
> Do you have a plan to get rid from 0.10? Or you are waiting october?

sorry I forgot to answer. I was waiting for October but I don't mind updating now if it's in your best interests

**Comment by TrySound** [comment]
@jonschlinkert Sure, you can add me. I'll take a look this evening.

**Comment by jonschlinkert** [comment]
done!

**Comment by TrySound** [comment]
@jonschlinkert And github too please :)

**Comment by jonschlinkert** [comment]
I thought I added you on github at the same time, I'll double check

**Comment by jonschlinkert** [comment]
yeah you should receive an invite, if you don't let me know and I'll look into it. thanks!

**Comment by TrySound** [comment]
Since some time github sends invitation, not just add as colloborator. Didn't figure out :)

**Comment by jonschlinkert** [comment]
I know exactly what you mean
